spring:
  application:
    name: rideShareBackend

  datasource:
    driver-class-name : org.postgresql.Driver
    url               : jdbc:postgresql://db:5432/${POSTGRES_DB}
    username          : ${POSTGRES_USERNAME}
    password          : ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret     : ${JWT_SECRET}
  expiration : 86400000