spring:
  application:
    name: Gigtern

  config:
    import: optional:file:${APP_ENV_FILE:.env}[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
