spring:
  application:
    name: rideShareBackend

  datasource:
    driver-class-name : org.postgresql.Driver
    url               : jdbc:postgresql://db:5432/${POSTGRES_DB}
    username          : ${POSTGRES_USERNAME}
    password          : ${POSTGRES_PASSWORD}

  jpa :
    hibernate :
      ddl-auto : create

jwt:
  secret     : "e0x7RzZtY0h4Sm5JcE9tMThhS2ZqM1kzVmE4dkQ3YjZzcjV6WFFjTjRpMFRrNlJKcm8xQ1d1TjZpOUlRczc3Sw=="
  expiration : 86400000
  public     :
    - "/api/v1/auth/register"
    - "/api/v1/auth/login"
    - "/api/v1/gigs"